const swaggerAutogen = require('swagger-autogen')()

// const outputFile = './swagger_output.json'
const endpointsFiles = ['./routers/personRouter.js'];
let doc = {
    "swagger": "2.0",
    "info": {
      "version": "1.0.0",
      "title": "Amway Smartdashboard Report System",
      "description": "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    "host": "uat.smart.amway.co.th",
    "basePath": "/uat",
    "tags": [
      {
        "name": "Report",
        "description": ""
      },
      {
        "name": "PRS",
        "description": ""
      },
      {
        "name": "Customize Report",
        "description": ""
      }
    ],
    "schemes": [
      "https"
    ],
    "securityDefinitions": {
      "Bearer": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "header",
        "description": ">-Enter the token with the `Bearer: ` prefix, e.g. \"Bearer token\""
      }
    },
    "consumes": [
      "application/json"
    ],
    "produces": [
      "application/json"
    ],
    "paths": {
      "/api/businessnature-change": {
        "get": {
          "tags": [
            "Report"
          ],
          "description": "get businessnature change",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "abos",
              "in": "query",
              "description": "abos",
              "required": true,
              "type": "string"
            },
            {
              "name": "procd",
              "in": "query",
              "description": "procd fix memberupgrade",
              "required": true,
              "type": "string"
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  },
                  "item": {
                    "$ref": "#/definitions/GetBusinessnatureChangeResponseModel"
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "401": {
              "description": "Unthorized",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "500": {
              "description": "Server Failure."
            }
          },
          "security": [
            {
              "Bearer": []
            }
          ]
        }
      },
      "/api/returnreport": {
        "get": {
          "tags": [
            "Report"
          ],
          "description": "get return report",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "abos",
              "in": "query",
              "description": "abos number limit 10",
              "required": true,
              "type": "string"
            },
            {
              "name": "period",
              "in": "query",
              "description": "period format YYYYMM",
              "required": true,
              "type": "string"
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  },
                  "item": {
                    "$ref": "#/definitions/GetReturnReportResponseModel"
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "401": {
              "description": "Unthorized",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "500": {
              "description": "Server Failure."
            }
          },
          "security": [
            {
              "Bearer": []
            }
          ]
        }
      },
      "/api/prs_getwarrantybyabolist": {
        "post": {
          "tags": [
            "PRS"
          ],
          "description": "get warranty by abo list",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "body",
              "in": "body",
              "description": "get warranty",
              "schema": {
                "$ref": "#/definitions/WarrantyDetailByABOListRequestModel"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "401": {
              "description": "Unthorized",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "500": {
              "description": "Server Failure."
            }
          },
          "security": [
            {
              "Bearer": []
            }
          ]
        }
      },
      "/api/prs_updatepart": {
        "post": {
          "tags": [
            "PRS"
          ],
          "description": "update spare part",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "body",
              "in": "body",
              "description": "Update spare part",
              "schema": {
                "$ref": "#/definitions/UpdatePartRequestModel"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "401": {
              "description": "Unthorized",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "500": {
              "description": "Server Failure."
            }
          },
          "security": [
            {
              "Bearer": []
            }
          ]
        }
      },
      "/api/prs_updateproductinfo": {
        "post": {
          "tags": [
            "PRS"
          ],
          "description": "update product info",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "body",
              "in": "body",
              "description": "Update product info",
              "schema": {
                "$ref": "#/definitions/UpdateProductInfoRequestModel"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "401": {
              "description": "Unthorized",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "500": {
              "description": "Server Failure."
            }
          },
          "security": [
            {
              "Bearer": []
            }
          ]
        }
      },
      "/api/getCustomRptStaff": {
        "get": {
          "tags": [
            "Customize Report"
          ],
          "description": "get custom report staff ",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "page",
              "in": "query",
              "description": "page fix abosetting",
              "required": true,
              "type": "string"
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  },
                  "data": {
                    "$ref": "#/definitions/GetCustomRptStaffResponseModel"
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "401": {
              "description": "Unthorized",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "500": {
              "description": "Server Failure."
            }
          },
          "security": [
            {
              "Bearer": []
            }
          ]
        }
      },
      "/api/getCustomRptWidget": {
        "get": {
          "tags": [
            "Customize Report"
          ],
          "description": "get custom report widget",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "group",
              "in": "query",
              "description": "widgetGroup",
              "required": false,
              "type": "string"
            },
            {
              "name": "type",
              "in": "query",
              "description": "widgetType",
              "required": false,
              "type": "string"
            },
            {
              "name": "code",
              "in": "query",
              "description": "widgetCode",
              "required": false,
              "type": "string"
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  },
                  "data": {
                    "$ref": "#/definitions/GetCustomRptWidgetResponseModel"
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "401": {
              "description": "Unthorized",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "500": {
              "description": "Server Failure."
            }
          },
          "security": [
            {
              "Bearer": []
            }
          ]
        }
      },
      "/api/getAboCustomTarget": {
        "get": {
          "tags": [
            "Customize Report"
          ],
          "description": "get abo custom setting",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "abo",
              "in": "query",
              "description": "abo number",
              "required": true,
              "type": "string"
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  },
                  "data": {
                    "$ref": "#/definitions/GetAboCustomTargetResponseModel"
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "401": {
              "description": "Unthorized",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "500": {
              "description": "Server Failure."
            }
          },
          "security": [
            {
              "Bearer": []
            }
          ]
        }
      },
      "/api/getAboCustomPined": {
        "get": {
          "tags": [
            "Customize Report"
          ],
          "description": "get abo custom setting",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "abo",
              "in": "query",
              "description": "abo number",
              "required": true,
              "type": "string"
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  },
                  "data": {
                    "$ref": "#/definitions/GetAboCustomPinedResponseModel"
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "401": {
              "description": "Unthorized",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "500": {
              "description": "Server Failure."
            }
          },
          "security": [
            {
              "Bearer": []
            }
          ]
        }
      },
      "/api/aboCustomGetTemplate": {
        "get": {
          "tags": [
            "Customize Report"
          ],
          "description": "get abo custom template",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "aboNo",
              "in": "query",
              "description": "abo number",
              "required": true,
              "type": "string"
            },
            {
              "name": "templateId",
              "in": "query",
              "description": "template id",
              "required": true,
              "type": "string"
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  },
                  "data": {
                    "$ref": "#/definitions/GetAboCustomTemplateResponseModel"
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "401": {
              "description": "Unthorized",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "500": {
              "description": "Server Failure."
            }
          },
          "security": [
            {
              "Bearer": []
            }
          ]
        }
      },
      "/api/aboCustomListTemplate": {
        "get": {
          "tags": [
            "Customize Report"
          ],
          "description": "get abo custom list template",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "aboNo",
              "in": "query",
              "description": "abo number",
              "required": true,
              "type": "string"
            },
            {
              "name": "templateType",
              "in": "query",
              "description": "template type",
              "required": false,
              "type": "string"
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  },
                  "data": {
                    "$ref": "#/definitions/GetAboCustomListTemplateResponseModel"
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "401": {
              "description": "Unthorized",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "500": {
              "description": "Server Failure."
            }
          },
          "security": [
            {
              "Bearer": []
            }
          ]
        }
      },
      "/api/aboCustomAddnewTemplate": {
        "post": {
          "tags": [
            "Customize Report"
          ],
          "description": "add new abo custom template",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "body",
              "in": "body",
              "description": "add new template",
              "schema": {
                "$ref": "#/definitions/AboCustomAddnewTemplateRequestModel"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "401": {
              "description": "Unthorized",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "500": {
              "description": "Server Failure."
            }
          },
          "security": [
            {
              "Bearer": []
            }
          ]
        }
      },
      "/api/aboCustomUpdateTemplate": {
        "post": {
          "tags": [
            "Customize Report"
          ],
          "description": "update abo custom template",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "body",
              "in": "body",
              "description": "update template",
              "schema": {
                "$ref": "#/definitions/AboCustomUpdateTemplateRequestModel"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "401": {
              "description": "Unthorized",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "500": {
              "description": "Server Failure."
            }
          },
          "security": [
            {
              "Bearer": []
            }
          ]
        }
      },
      "/api/aboCustomDeleteTemplate": {
        "post": {
          "tags": [
            "Customize Report"
          ],
          "description": "delete abo custom template",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "body",
              "in": "body",
              "description": "delete template",
              "schema": {
                "$ref": "#/definitions/AboCustomDeleteTemplateRequestModel"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "401": {
              "description": "Unthorized",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "500": {
              "description": "Server Failure."
            }
          },
          "security": [
            {
              "Bearer": []
            }
          ]
        }
      },
      "/api/setAboCustomTarget": {
        "post": {
          "tags": [
            "Customize Report"
          ],
          "description": "set abo custom target",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "body",
              "in": "body",
              "description": "set target team",
              "schema": {
                "$ref": "#/definitions/SetAboCustomTargetRequestModel"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "401": {
              "description": "Unthorized",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "500": {
              "description": "Server Failure."
            }
          },
          "security": [
            {
              "Bearer": []
            }
          ]
        }
      },
      "/api/updateAboCustomPined": {
        "post": {
          "tags": [
            "Customize Report"
          ],
          "description": "update Pined",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "body",
              "in": "body",
              "description": "update Pined",
              "schema": {
                "$ref": "#/definitions/UpdateAboCustomPinedRequestModel"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "401": {
              "description": "Unthorized",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "500": {
              "description": "Server Failure."
            }
          },
          "security": [
            {
              "Bearer": []
            }
          ]
        }
      },
      "/api/aboCustomSearchProduct": {
        "get": {
          "tags": [
            "Customize Report"
          ],
          "description": "Search Product Assignment",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "productCode",
              "in": "query",
              "description": "productCode (Ex. 123TH or 123TH,121584)",
              "required": false,
              "type": "string"
            },
            {
              "name": "textsearch",
              "in": "query",
              "description": "textsearch",
              "required": false,
              "type": "string"
            },
            {
              "name": "orderBy",
              "in": "query",
              "description": "orderBy (code or name)",
              "required": false,
              "type": "string"
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  },
                  "resultCount": {
                    "type": "number",
                    "example": 0
                  },
                  "products": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/AboCustomSearchProductResponseModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "401": {
              "description": "Unthorized",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "500": {
              "description": "Server Failure."
            }
          },
          "security": [
            {
              "Bearer": []
            }
          ]
        }
      },
      "/api/aboCustomGetProductAssignment": {
        "get": {
          "tags": [
            "Customize Report"
          ],
          "description": "Abo Custom Get Product Assignment",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "aboNo",
              "in": "query",
              "description": "aboNo",
              "required": true,
              "type": "string"
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  },
                  "aboNo": {
                    "type": "string",
                    "example": "string"
                  },
                  "downline": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "example": [
                        "str1",
                        "str2",
                        "str3"
                      ]
                    }
                  },
                  "productList": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/AboCustomGetProductAssignmentResponseModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "401": {
              "description": "Unthorized",
              "schema": {
                "type": "object",
                "properties": {
                  "success": {
                    "type": "boolean",
                    "example": false
                  },
                  "requestId": {
                    "type": "string",
                    "example": "string"
                  },
                  "error": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ErrorModel"
                    }
                  }
                },
                "xml": {
                  "name": "main"
                }
              }
            },
            "500": {
              "description": "Server Failure."
            }
          },
          "security": [
            {
              "Bearer": []
            }
          ]
        }
      }
    },
    "definitions": {
      "WarrantyDetailByABOListRequestModel": {
        "type": "object",
        "properties": {
          "accountCode": {
            "type": "string",
            "example": "string"
          },
          "periodFrom": {
            "type": "string",
            "example": "string"
          },
          "periodTo": {
            "type": "string",
            "example": "string"
          },
          "paginationToken": {
            "type": "string",
            "example": "string"
          }
        }
      },
      "UpdatePartRequestModel": {
        "type": "object",
        "properties": {
          "productCode": {
            "type": "string",
            "example": "string"
          },
          "serialNumber": {
            "type": "string",
            "example": "string"
          },
          "partProductCode": {
            "type": "string",
            "example": "string"
          },
          "partSerialNumber": {
            "type": "string",
            "example": "string"
          },
          "changeDate": {
            "type": "string",
            "example": "string"
          },
          "channel": {
            "type": "string",
            "example": "string"
          }
        }
      },
      "UpdateProductInfoRequestModel": {
        "type": "object",
        "properties": {
          "productCode": {
            "type": "string",
            "example": "string"
          },
          "serialNumber": {
            "type": "string",
            "example": "string"
          },
          "productNickName": {
            "type": "string",
            "example": "string"
          },
          "custNickName": {
            "type": "string",
            "example": "string"
          },
          "custNote": {
            "type": "string",
            "example": "string"
          }
        }
      },
      "GetCustomRptStaffResponseModel": {
        "type": "object",
        "properties": {
          "pageName": {
            "type": "string",
            "example": "string"
          },
          "pageKey": {
            "type": "string",
            "example": "string"
          }
        }
      },
      "GetAboCustomTargetResponseModel": {
        "type": "object",
        "properties": {
          "aboNo": {
            "type": "string",
            "example": "string"
          },
          "targetTeam": {
            "type": "string",
            "example": "string"
          },
          "targetPerson": {
            "type": "string",
            "example": "string"
          }
        }
      },
      "GetAboCustomPinedResponseModel": {
        "type": "object",
        "properties": {
          "aboNo": {
            "type": "string",
            "example": "string"
          },
          "pinnedTeam": {
            "type": "array",
            "example": [
              "string"
            ],
            "items": {
              "type": "string"
            }
          },
          "pinnedPerson": {
            "type": "array",
            "example": [
              "string"
            ],
            "items": {
              "type": "string"
            }
          }
        }
      },
      "GetCustomRptWidgetResponseModel": {
        "type": "object",
        "properties": {
          "widgetList": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "Code": {
                  "type": "string",
                  "example": "string"
                },
                "name": {
                  "type": "string",
                  "example": "string"
                },
                "group": {
                  "type": "string",
                  "example": "string"
                },
                "type": {
                  "type": "string",
                  "example": "string"
                },
                "flagActive": {
                  "type": "boolean",
                  "example": false
                },
                "size": {
                  "type": "string",
                  "example": "string"
                }
              }
            }
          }
        }
      },
      "GetBusinessnatureChangeResponseModel": {
        "type": "object",
        "properties": {
          "aboNum": {
            "type": "string",
            "example": "string"
          },
          "lifeCycleList": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "effectiveDate": {
                  "type": "string",
                  "example": "string"
                },
                "processCd": {
                  "type": "string",
                  "example": "string"
                },
                "reasonCd": {
                  "type": "string",
                  "example": "string"
                },
                "transactionDate": {
                  "type": "string",
                  "example": "string"
                }
              }
            }
          }
        }
      },
      "GetReturnReportResponseModel": {
        "type": "object",
        "properties": {
          "uplineAbo": {
            "type": "string",
            "example": "string"
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "aboNum": {
                  "type": "string",
                  "example": "string"
                },
                "returnTrans": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "returnCode": {
                        "type": "string",
                        "example": "string"
                      },
                      "orderCode": {
                        "type": "string",
                        "example": "string"
                      },
                      "returnDatetime": {
                        "type": "string",
                        "example": "string"
                      },
                      "returnChannel": {
                        "type": "string",
                        "example": "string"
                      },
                      "reasonCode": {
                        "type": "string",
                        "example": "string"
                      },
                      "reasonDesc": {
                        "type": "string",
                        "example": "string"
                      },
                      "note": {
                        "type": "string",
                        "example": "string"
                      },
                      "totalBvReturn": {
                        "type": "number",
                        "example": 0
                      },
                      "totalPvReturn": {
                        "type": "number",
                        "example": 0
                      },
                      "returnItem": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "productCode": {
                              "type": "string",
                              "example": "string"
                            },
                            "productName": {
                              "type": "string",
                              "example": "string"
                            },
                            "returnQuantity": {
                              "type": "number",
                              "example": 0
                            },
                            "returnPv": {
                              "type": "number",
                              "example": 0
                            },
                            "returnBv": {
                              "type": "number",
                              "example": 0
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "GetAboCustomTemplateResponseModel": {
        "type": "object",
        "properties": {
          "templateId": {
            "type": "string",
            "example": "string"
          },
          "templateName": {
            "type": "string",
            "example": "string"
          },
          "widgetList": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "widgetCode": {
                  "type": "string",
                  "example": "string"
                },
                "position": {
                  "type": "string",
                  "example": "string"
                },
                "size": {
                  "type": "string",
                  "example": "string"
                }
              }
            }
          }
        }
      },
      "AboCustomAddnewTemplateRequestModel": {
        "type": "object",
        "properties": {
          "aboNo": {
            "type": "string",
            "example": "string"
          },
          "templateName": {
            "type": "string",
            "example": "string"
          },
          "templateType": {
            "type": "string",
            "example": "string"
          },
          "flagUse": {
            "type": "boolean",
            "example": false
          },
          "widget": {
            "type": "string",
            "example": "string"
          },
          "createUser": {
            "type": "string",
            "example": "string"
          }
        }
      },
      "AboCustomUpdateTemplateRequestModel": {
        "type": "object",
        "properties": {
          "aboNo": {
            "type": "string",
            "example": "string"
          },
          "templateId": {
            "type": "string",
            "example": "string"
          },
          "templateName": {
            "type": "string",
            "example": "string"
          },
          "templateType": {
            "type": "string",
            "example": "string"
          },
          "flagUse": {
            "type": "boolean",
            "example": false
          },
          "widget": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "widgetCode": {
                  "type": "string",
                  "example": "string"
                },
                "widgetGroup": {
                  "type": "string",
                  "example": "string"
                },
                "widgetType": {
                  "type": "string",
                  "example": "string"
                },
                "position": {
                  "type": "string",
                  "example": "string"
                }
              }
            }
          },
          "updateUser": {
            "type": "string",
            "example": "string"
          }
        }
      },
      "AboCustomDeleteTemplateRequestModel": {
        "type": "object",
        "properties": {
          "aboNo": {
            "type": "string",
            "example": "string"
          },
          "templateId": {
            "type": "string",
            "example": "string"
          }
        }
      },
      "GetAboCustomListTemplateResponseModel": {
        "type": "object",
        "properties": {
          "aboNo": {
            "type": "string",
            "example": "string"
          },
          "templateList": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "templateId": {
                  "type": "string",
                  "example": "string"
                },
                "templateName": {
                  "type": "string",
                  "example": "string"
                },
                "templateType": {
                  "type": "string",
                  "example": "string"
                },
                "aboNo": {
                  "type": "string",
                  "example": "string"
                },
                "flagUse": {
                  "type": "boolean",
                  "example": false
                },
                "updateDate": {
                  "type": "string",
                  "example": "string"
                },
                "shareTemplateIdBy": {
                  "type": "string",
                  "example": "string"
                },
                "shareTemplateId": {
                  "type": "string",
                  "example": "string"
                },
                "flagDefault": {
                  "type": "boolean",
                  "example": false
                },
                "starterTemplate": {
                  "type": "string",
                  "example": "string"
                }
              }
            }
          }
        }
      },
      "SetAboCustomTargetRequestModel": {
        "type": "object",
        "properties": {
          "aboNo": {
            "type": "string",
            "example": "string"
          },
          "targetTeam": {
            "type": "string",
            "example": "string"
          },
          "updateDate": {
            "type": "string",
            "example": "string"
          },
          "targetGPV": {
            "type": "number",
            "example": 0
          }
        }
      },
      "UpdateAboCustomPinedRequestModel": {
        "type": "object",
        "properties": {
          "aboNo": {
            "type": "string",
            "example": "string"
          },
          "pinnedAbo": {
            "type": "string",
            "example": "string"
          },
          "pinnedType": {
            "type": "string",
            "example": "string"
          },
          "actionType": {
            "type": "string",
            "example": "string"
          },
          "updateDate": {
            "type": "string",
            "example": "string"
          }
        }
      },
      "AboCustomSearchProductResponseModel": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string",
            "example": "string"
          },
          "name": {
            "type": "string",
            "example": "string"
          },
          "pv": {
            "type": "number",
            "example": 0
          },
          "bv": {
            "type": "number",
            "example": 0
          },
          "image": {
            "type": "string",
            "example": "string"
          }
        }
      },
      "AboCustomGetProductAssignmentResponseModel": {
        "type": "object",
        "properties": {
          "itemAliasCode": {
            "type": "string",
            "example": "string"
          },
          "name": {
            "type": "string",
            "example": "string"
          },
          "image": {
            "type": "string",
            "example": "string"
          },
          "productLifeCycle": {
            "type": "string",
            "example": "string"
          },
          "consumePeriod": {
            "type": "string",
            "example": "string"
          },
          "createDate": {
            "type": "string",
            "example": "string"
          }
        }
      },
      "ErrorModel": {
        "type": "object",
        "properties": {
          "errorCode": {
            "type": "string",
            "example": "string"
          },
          "errorMsg": {
            "type": "string",
            "example": "string"
          },
          "errorDebug": {
            "type": "string",
            "example": "string"
          }
        }
      }
    },
    "security": {
      "Bearer": []
    }
  };
swaggerAutogen(doc)